---
- name: Intall environmental components if needed
  yum:
    name:
      - "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python3-devel
    - python3-rpm
    - git
    - dnf
  when: "'{{ item }}' not in required_packages_check.ansible_facts.packages"

- name: Install python3 packages
  pip:
    name:
      - rpm
      - dnf
    executable: pip3
    state: forcereinstall
  vars:
    ansible_python_interpreter: /usr/bin/python3
